version: '3.8'

services:
  vennekredsen:
    container_name: vennekredsen-hjemmeside
    restart: unless-stopped
    image: ghcr.io/jfriisj/vennekredsen/frontend:latest
    ports:
      - "85:80"
    networks:
      - vennekredsen_net
      - cloudflare
    depends_on:
      - api

  api:
    container_name: vennekredsen-api
    restart: unless-stopped
    image: ghcr.io/jfriisj/vennekredsen/api:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - vennekredsen_net
      - cloudflare
    depends_on:
      - db

  db:
    container_name: vennekredsen-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vennekredsen_net
      
  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: vennekredsen_cloudflare_tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${INTERNAL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - vennekredsen_net
      - cloudflare

networks:
  vennekredsen_net:
  cloudflare:
    external: true

volumes:
  db_data: