services:
  vennekredsen:
    container_name: vennekredsen-hjemmeside
    restart: unless-stopped
    image: ghcr.io/jfriisj/vennekredsen:latest
    ports:
      - "85:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true
