services:
  vennekredsen:
    container_name: vennekredsen-hjemmeside
    restart: unless-stopped
    image: ghcr.io/jfriisj/vennekredsen/frontend:latest
    ports:
      - "85:80"
    networks:
      - vennekredsen_net
      - cloudflare
    depends_on:
      - api

  api:
    container_name: vennekredsen-api
    restart: unless-stopped
    image: ghcr.io/jfriisj/vennekredsen/api:latest
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - POSTGRES_DB=${POSTGRES_DB:-vennekredsen_prod}
      - POSTGRES_USER=${POSTGRES_USER:-vennekredsen_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change_this_password}
      - JWT_SECRET=${JWT_SECRET:-change_this_jwt_secret}
    ports:
      - "5000:5000"  # Expose API port like in local setup
    networks:
      - vennekredsen_net
      - cloudflare
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: vennekredsen-db
    image: postgres:15  # Use same version as local
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vennekredsen_prod}
      POSTGRES_USER: ${POSTGRES_USER:-vennekredsen_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_this_password}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vennekredsen_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-vennekredsen_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: vennekredsen_cloudflare_tunnel
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${INTERNAL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - vennekredsen_net
      - cloudflare

networks:
  vennekredsen_net:
  cloudflare:
    external: false

volumes:
  db_data: