version: '3.8'

services:
  vennekredsen:
    container_name: vennekredsen-hjemmeside
    restart: unless-stopped
    build: ./frontend
    ports:
      - "85:80"
    networks:
      - cloudflare
    depends_on:
      - api

  api:
    container_name: vennekredsen-api
    restart: unless-stopped
    build: ./api
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - cloudflare
    depends_on:
      - db

  db:
    container_name: vennekredsen-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: vennekredsen_db
      POSTGRES_USER: vennekredsen
      POSTGRES_PASSWORD: hemmeligkode
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true

volumes:
  db_data: