name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # Build API image
    - name: Build API Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./api
        file: ./api/Dockerfile
        push: false
        load: true
        tags: vennekredsen-api:latest
        cache-from: type=gha,scope=api
        cache-to: type=gha,scope=api,mode=max
    
    # Build Frontend image
    - name: Build Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: false
        load: true
        tags: vennekredsen-frontend:latest
        cache-from: type=gha,scope=frontend
        cache-to: type=gha,scope=frontend,mode=max
    
    # Test with Docker Compose V2
    - name: Test with Docker Compose
      run: |
        docker image ls
        docker compose config
        docker compose build
        docker compose up -d
        sleep 10  # Give services time to start
        docker compose ps
        docker compose logs
        docker compose down