name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  vennekredsen:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 'ghcr.io/jfriisj/vennekredsen:latest'
