name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  vennekredsen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 'ghcr.io/jfriisj/vennekredsen:latest'
