name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  vennekredsen: # This is the name of the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: macbre/push-to-ghcr@master
        with:
          image_name: 'jfriisj/vennekredsen'
          github_token: ${{ secrets.TOKEN }}
